### ISSUE TITLE
Description database

### ISSUE THREAD

**Issue by CK7** [shafferm/DRAM#14]
Executing DRAM-setup.py print_config resulted with a path for all the databases except for the description database (not sure what it is). The information I get for this database is

Description db: None

I ran the  command DRAM-setup.py update_description_db which I assumed would solve the issue. The command seem to have completed successfully, but when I ran DRAM-setup.py print_config again I still got no description db. What should I do to fix that? I have a file called description_db.sqlite in my DRAM_data directory.

**Comment by shafferm** [comment]
That definitely does not seem right. I found a bug where if the description db location is not set when you run `populate_description_db` then the database won't be saved correctly. I will issue a fix for this.

Because you have a description_db.sqlite we should be able to fix this. Can you try running `sudo DRAM-setup.py set_database_locations --description_db_loc {path to your description_db.sqlite}` and then `print_config` to see if that worked. Sudo because of your manual installation. Hopefully that will set the path directly. When you ran `update_description_db` did you get an error? If that doesn't work then we can try editing the CONFIG file manually.

**Comment by CK7** [comment]
This command:

sudo DRAM-setup.py set_database_locations --description_db_loc {path to your description_db.sqlite}

worked and print_config listed the correct location. I was able also to run DRAM.py annotation and distill after that.
