### ISSUE TITLE
DRAM did not install

### ISSUE THREAD

**Issue by gtrubl** [shafferm/DRAM#17]
I was following the protocol and kept getting the error that DRAM could not be found when trying "DRAM-setup.py prepare_databases --output_dir DRAM_data".

I had to add "conda install DRAM" for it to work. I guess the yaml file only include the dependencies of DRAM, but not DRAM itself.

It is working now. Also, thanks for the time estimate.

-Gary

**Comment by shafferm** [comment]
Hi Gary,

DRAM is not available on bioconda yet. We are waiting to get DRAM a bit more stable before we do that. You need to install DRAM from pip with `pip install DRAM-bio` after you set up the conda environment.

Actually I can have pip dependencies in an environment file. I have updated the environment.yaml so that DRAM-bio is installed from pip during conda environment set up. Documentation has been updated to reflect this. Thanks for the idea!
