### ISSUE TITLE
Unable to link to existing uniref DB if using --skip_uniref step

### ISSUE THREAD

**Issue by nixon444** [shafferm/DRAM#18]
I am trying to install DRAM on a VM with 64 GB RAM. I have managed to setup the databses but only when using the --skip_uniref flag as without this the process maxes out my memory. However my server already has the uniref90 database so I have tried linking this into the database set-up step. The issue is that, while using the --skip_uniref flag gets around the memory issue, if I also try to use the --uniref_loc flag at the same time this doesn't work - the uniref database is listed as 'None' when I run the print_config step. It seems that using the --skip_uniref flag serves to cancel this step out?

If so, is there a way of linking my existing uniref database to the DRAM-installed databases after all other databases have been prepared? I want to maximise the number of databases I can call upon when running bins through the program and I don't have a KEGG subscription, so uniref is valuable here.

**Comment by shafferm** [comment]
DRAM does not use the UniRef90 database directly but first processes it so that MMSeqs2 can be used. MMSeqs2 takes ~500 GB of RAM to process the full UniRef90 database FASTA . If you have a version of the UniRef90 database processed with MMSeqs2 then we could get around this using `DRAM-setup.py set_database_locations`. Using `--skip_uniref` causes DRAM-setup.py to ignore the value of `--uniref_loc` which is why that is happening.

If you don't have a MMSeqs2 processed version of UniRef90 then 64 GB is not enough to get this done. It's fine that you don't have a KEGG subscription because KOfam will be used to give you KEGG Orthology annotations. You also will get annotations from all the other databases that DRAM uses if you are not able to get UniRef90 working.

Finally we are experimenting with using different UniProt subsets and if you would like to try that then you could try passing a smaller UniProt subset to DRAM using `--uniref_loc` during the `prepare_databases` step. This would still give you the UniProt annotations with the most information but use much less memory during processing and annotation. For this I'd recommend using the reviewed (Swiss-Prot) set from https://www.uniprot.org/downloads.

**Comment by nixon444** [comment]
Aaaah ok, thanks for this. I will have a play on my VM without the uniref database. We are also installing DRAM on the university server which can provide much more memory so I will have access to the MMSeq2-processed uniref database via that installation. 

Thanks for the comprehensive response, much appreciated.
