### ISSUE TITLE
Use prebuild mmseqs databases

### ISSUE THREAD

**Issue by SilasK** [shafferm/DRAM#30]
Hey @shafferm , Very cool pipeline. I think the building of the databases takes so long and is so memory intensive because you download big databases and create mmseqs databases. 

Have you thought about using the rebuild mmseqs databases or storing yours on zendoo for example.

**Comment by shafferm** [comment]
Hey @SilasK,

We have a zenodo repository with the databases needed for a minimal installation. It is available here: https://zenodo.org/record/3827510. You could download all the files from here and then use `DRAM-setup.py set_database_locations` to configure your setup. This is what the KBase DRAM app uses. There is a problem with the Pfam databases uploaded there where no hits are found but an error isn't found either. All the other databases work. We have not widely publicized this because of the problem with the Pfam database as well as the fact that this is a minimal install. We didn't add uniref90 there as the processed databases are around 400 GB which is way bigger than the 50 GB per dataset limit.

We plan on having this as a more official install path in the future. It's on our to do list!
