### ISSUE TITLE
Dram-v annotate ValueError: No objects to concatenate

### ISSUE THREAD

**Issue by bbica** [shafferm/DRAM#32]
Hi there 

While trying to run Dram-v annotate I keep getting the following error:

`ko_hits_sig = pd.concat(is_sig)
  File "/share/apps/opt/miniconda3/envs/DRAM/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 271, in concat
    op = _Concatenator(
  File "/share/apps/opt/miniconda3/envs/DRAM/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 329, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate`

The content of the annotate folder created has only the Working_dir and the vMAGs. No annotate.tsv

Do you have an idea why this is happening?

**Comment by shafferm** [comment]
This looks like a version of the bug from #27. A fix for that issue has not been pushed to pip or conda yet but you can update your DRAM version from the master branch here. 

Tou can save your config file, update your DRAM installation from the master branch of this repo and then reimport your config file. Instructions on how to do this are here: https://github.com/shafferm/DRAM/wiki/5.-Managing,-updating-or-moving-a-DRAM-installation-and-databases#updating-your-dram-installation. Otherwise I will update this issue when a new version with the fix has been released. To get around this problem without updating I would recommend dropping this contig but throwing away data is never nice.

**Comment by bbica** [comment]
Thank you for you time and response

Updated Dram out of conda did the job. All seems to be running fine.

Thanks again!
