### ISSUE TITLE
Add option to use amino acid fasta instead of nucleotide fasta

### ISSUE THREAD

**Issue by qiyanang** [shafferm/DRAM#42]
Hi DRAM team, 

Would you be able to add an option to the DRAM.py annotate command that allows users to input pre-generated amino acid fasta files from prodigal as opposed to using only nucleotide fasta (then running prodigal through DRAM)?

Happy to further explain my use case if this is something you would consider.

Thanks very much!

**Comment by shafferm** [comment]
You can do this with DRAM! There is another command called `DRAM.py annotate_genes` where you give a file (or path with wildcards) with amino acid sequences instead of bins. There are a few things it can't do because of the information that DRAM pulls from the prodigal headers but you get most of the DRAM experience. Let me know if you hit any snags using this as it is not a super popular feature so far and as a result isn't as battle tested as `DRAM.py annotate`.

**Comment by qiyanang** [comment]
Ah perfect, thanks for the clarification! The annotate_genes command seems to have worked on my test file :)
