### ISSUE TITLE
DRAM-v very slow

### ISSUE THREAD

**Issue by Thexiyang** [shafferm/DRAM#49]
Thanks for the nice tool! I am using the DRAM-v to annotate my viral contigs. Although I set threads to 50, the annotation process is very slow for hmmsearch. I am wondering if this parameter does not work for hmmsearch.

**Comment by shafferm** [comment]
DRAM-v takes a long time because of the size of the additional databases that are used to annotation viral contigs as well as the fact that we annotate viral contigs as if they were each their own genome. This means that there is extra time because the HMM searches take longer if you run them separately pre genome instead of all at once. We chose to do this because it makes your annotations more reproducible since the number of viruses you annotate at once will not affect the annotations given to each virus. The drawback is that annotations take a lot longer. We are going to be adding a flag soon that will allow users to annotate all viruses at once which will be MUCH faster but lose you that reproducibility. But we aren't there quite yet.
