### ISSUE TITLE
JavaScript Error: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by mw55309** [shafferm/DRAM#56]
Hello!

I did DRAM.py distill on ~2100 genomes and it split the output into product_0.html, product_1.html and product_2.html

I can only open product_2.html

The other two complain:

```
JavaScript Error: Maximum call stack size exceeded
This usually means there's a typo in your chart specification. See the javascript console for the full traceback.
```

I get this error in Edge and in Chrome. Firefox reports not error, but all three browsers simply display a blank page.

This could be a "size" problem - is there a way to chunk the output into more chunks?

Cheers
Mick

**Comment by shafferm** [comment]
I just pushed a fix to the master branch where a flag is added so that you can set the number of genomes per `product.html` output to get around this issue (607fda7). The flag is `--genomes_per_product`. I know others have had this issue as well. If you want to hack it with your own install then all you need to do is change the `GENOMES_PER_LIQUOR` value at the top of the `summarize_genomes.py` file.

But you have likely already figured this out. Thanks for being so helpful in these issues while I have been running behind @mw55309!
