### ISSUE TITLE
Standard Setup Database Size

### ISSUE THREAD

**Issue by bph6212ln** [shafferm/DRAM#7]
The wiki states "with a standard setup the processed DRAM databases take up about 20 GB of storage". After having installed DRAM and run what seemed to be the default setup:

`DRAM-setup.py prepare_databases --verbose --output_dir $DBDIR \`
`--kofam_ko_list_loc $DBDIR/kofam_ko_list.tsv.gz \`
`--kofam_hmm_loc $DBDIR/profiles.tar.gz \`
`--uniref_loc $DBDIR/uniref90.fasta.gz \`
`--pfam_loc $DBDIR/Pfam-A.full.gz \`
`--dbcan_loc $DBDIR/dbCAN-HMMdb-V8.txt \`
`--dbcan_fam_activities $DBDIR/CAZyDB.07312019.fam-activities.txt \`
`--vogdb_loc $DBDIR/vog.hmm.tar.gz \`
`--vog_annotations $DBDIR/vog.annotations.tsv.gz \`
`--peptidase_loc $DBDIR/pepunit.lib`

I ended up with 412G of database files after removing the gz files. (I ended up using the paths to avoid re-downloading the source dbs on each `prepare_databases` attempt having run into a number of failures due to memory, cpu, and software version mismatches.)

I presume the wiki is out of date. If not, how do I pare this down to a 'standard setup'? Most of our compute nodes don't have this much space to spare. Most of the space seems to be uniref90:

`300G Jun 26 18:55 uniref90.20200626.mmsdb.idx`
`13G Jun 26 16:31 uniref90.20200626.mmsdb_h`
`36G Jun 26 16:34 uniref90.20200626.mmsdb`

**Comment by shafferm** [comment]
Hey @bph6212ln,

Yeah this is out of date. It's also misleading because that is the size of the downloaded databases before they are processed. And UniRef grows every week so even that number is bigger now. I have updated the wiki to say that the fully installed size is ~500 gb.

You are right on that the problem, as usually when it comes to memory and disk usage issues with DRAM, is UniRef90. I would recommend getting rid of UniRef90. If you use KOfam instead of KEGG Genes and don't include UniRef90 then total database size is ~30 GB. Much more manageable. Also the DRAM distillation process does not use UniRef90 annotations so you would not be losing any of those capabilities by not including it. This is the setup we use in the KBase version of DRAM [link](https://narrative.kbase.us/#catalog/apps/kb_DRAM/run_kb_dram_annotate/beta) and we have not seen a major degradation in quality of distilled annotations.

Also let me know if any of the failures you ran into with versioning could be fixed with more specific version pins in our environment file and/or setup.py.
